// Generated by CoffeeScript 1.6.3
console.log("now loading...");

$.ajax({
  type: 'GET',
  url: 'http://www.akashi.ac.jp/data/timetable/timetable201310.xml',
  dataType: 'xml',
  success: function(xml) {
    var lectures;
    lectures = _.map($(xml).find('Lecture'), function(l) {
      return new Lecture(l);
    });
    return _.each(lectures, function(l) {
      var i, _i, _results;
      _results = [];
      for (i = _i = 1; _i <= 4; i = ++_i) {
        if (l.isToday() && l.isPeriod(i)) {
          _results.push($("#" + (l.eDept()) + (l.eCourse()) + l.grade + "+dd").append("" + i + ". <strong>" + l.name + "</strong> ＠" + l.location + "<br>"));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
  }
});
